#!/bin/bash
set -eux

# Precompile dependencies
julia --project=binder -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

# Install Pluto and register it as a Jupyter server extension
julia --project=binder -e 'using Pluto; Pluto.run(host="0.0.0.0", port=8888, launch_browser=false)'

