#!/bin/bash
exec julia --project=binder -e "using Pluto; Pluto.run(host=\"0.0.0.0\", port=8888, launch_browser=false, require_secret_for_open_links=false, require_secret_for_access=false, notebook=\"notebooks/hello.jl\")"
